function [dX,local_X] = get_symgen_step(dt,X,u,p)
%GET_SYMGEN_STEP
%    [DX,LOCAL_X] = GET_SYMGEN_STEP(DT,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    01-Dec-2017 22:29:17

F = u(1,:);
I = p(1,:);
a = p(2,:);
g = p(3,:);
m = p(4,:);
psi = X(3,:);
psi_dot = X(6,:);
theta = u(2,:);
x_dot = X(4,:);
y_dot = X(5,:);
dX = [x_dot;y_dot;psi_dot;(F.*cos(psi+theta))./m;-(g.*m-F.*sin(psi+theta))./m;-(F.*a.*sin(theta))./I];
if nargout > 1
    local_X = [(F.*cos(theta)-g.*m.*sin(psi))./m;(F.*sin(theta)-g.*m.*cos(psi))./m];
end
