addpath(...
'/home/slovak/vertical_landing/ACADOtoolkit/interfaces/matlab/acado', ...
'/home/slovak/vertical_landing/ACADOtoolkit/interfaces/matlab/acado/functions', ...
'/home/slovak/vertical_landing/ACADOtoolkit/interfaces/matlab/acado/keywords', ...
'/home/slovak/vertical_landing/ACADOtoolkit/interfaces/matlab/acado/packages', ...
'/home/slovak/vertical_landing/ACADOtoolkit/interfaces/matlab/integrator', ...
'/home/slovak/vertical_landing/ACADOtoolkit/interfaces/matlab/shared', ...
'/home/slovak/vertical_landing/ACADOtoolkit/interfaces/matlab/bin', ...
'/home/slovak/vertical_landing/ACADOtoolkit/interfaces/matlab/bin/acado', ...
'/home/slovak/vertical_landing/ACADOtoolkit/interfaces/matlab/bin/acado/casadi', ...
'/home/slovak/vertical_landing/ACADOtoolkit/interfaces/matlab/bin/acado/code_generation', ...
'/home/slovak/vertical_landing/ACADOtoolkit/interfaces/matlab/bin/acado/code_generation/templates', ...
'/home/slovak/vertical_landing/ACADOtoolkit/interfaces/matlab/bin/acado/qpOASES');
